from _typeshed import Incomplete

__all__ = ['histogram', 'histogramdd', 'histogram_bin_edges']

def histogram_bin_edges(a, bins: int = 10, range: Incomplete | None = None, weights: Incomplete | None = None): ...
def histogram(a, bins: int = 10, range: Incomplete | None = None, density: Incomplete | None = None, weights: Incomplete | None = None): ...
def histogramdd(sample, bins: int = 10, range: Incomplete | None = None, density: Incomplete | None = None, weights: Incomplete | None = None): ...
