__all__ = ['sqrt', 'log', 'log2', 'logn', 'log10', 'power', 'arccos', 'arcsin', 'arctanh']

def sqrt(x): ...
def log(x): ...
def log10(x): ...
def logn(n, x): ...
def log2(x): ...
def power(x, p): ...
def arccos(x): ...
def arcsin(x): ...
def arctanh(x): ...
