from _typeshed import Incomplete

__all__ = ['column_stack', 'row_stack', 'dstack', 'array_split', 'split', 'hsplit', 'vsplit', 'dsplit', 'apply_over_axes', 'expand_dims', 'apply_along_axis', 'kron', 'tile', 'take_along_axis', 'put_along_axis']

def take_along_axis(arr, indices, axis): ...
def put_along_axis(arr, indices, values, axis) -> None: ...
def apply_along_axis(func1d, axis, arr, *args, **kwargs): ...
def apply_over_axes(func, a, axes): ...
def expand_dims(a, axis): ...
def row_stack(tup, *, dtype: Incomplete | None = None, casting: str = 'same_kind'): ...
def column_stack(tup): ...
def dstack(tup): ...
def array_split(ary, indices_or_sections, axis: int = 0): ...
def split(ary, indices_or_sections, axis: int = 0): ...
def hsplit(ary, indices_or_sections): ...
def vsplit(ary, indices_or_sections): ...
def dsplit(ary, indices_or_sections): ...
def kron(a, b): ...
def tile(A, reps): ...
