from _typeshed import Incomplete

__all__ = ['broadcast_to', 'broadcast_arrays', 'broadcast_shapes']

class DummyArray:
    __array_interface__: Incomplete
    base: Incomplete
    def __init__(self, interface, base: Incomplete | None = None) -> None: ...

def broadcast_to(array, shape, subok: bool = False): ...
def broadcast_shapes(*args): ...
def broadcast_arrays(*args, subok: bool = False): ...
