from _typeshed import Incomplete

__all__ = ['iscomplexobj', 'isrealobj', 'imag', 'iscomplex', 'isreal', 'nan_to_num', 'real', 'real_if_close', 'typename', 'mintypecode', 'common_type']

def mintypecode(typechars, typeset: str = 'GDFgdf', default: str = 'd'): ...
def real(val): ...
def imag(val): ...
def iscomplex(x): ...
def isreal(x): ...
def iscomplexobj(x): ...
def isrealobj(x): ...
def nan_to_num(x, copy: bool = True, nan: float = 0.0, posinf: Incomplete | None = None, neginf: Incomplete | None = None): ...
def real_if_close(a, tol: int = 100): ...
def typename(char): ...
def common_type(*arrays): ...
