from _typeshed import Incomplete

__all__ = ['fix', 'isneginf', 'isposinf']

def fix(x, out: Incomplete | None = None): ...
def isposinf(x, out: Incomplete | None = None): ...
def isneginf(x, out: Incomplete | None = None): ...
