from _typeshed import Incomplete

__all__ = ['get_include', 'info', 'show_runtime']

def show_runtime() -> None: ...
def get_include(): ...

class _Deprecate:
    old_name: Incomplete
    new_name: Incomplete
    message: Incomplete
    def __init__(self, old_name: Incomplete | None = None, new_name: Incomplete | None = None, message: Incomplete | None = None) -> None: ...
    def __call__(self, func, *args, **kwargs): ...

def info(object: Incomplete | None = None, maxwidth: int = 76, output: Incomplete | None = None, toplevel: str = 'numpy') -> None: ...
