from _typeshed import Incomplete

__all__ = ['NumpyVersion']

class NumpyVersion:
    __module__: str
    vstring: Incomplete
    version: Incomplete
    pre_release: str
    is_devversion: Incomplete
    def __init__(self, vstring) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
