import numpy as np
from pandas._typing import npt as npt

def cumsum(values: np.ndarray, mask: npt.NDArray[np.bool_], *, skipna: bool = True): ...
def cumprod(values: np.ndarray, mask: npt.NDArray[np.bool_], *, skipna: bool = True): ...
def cummin(values: np.ndarray, mask: npt.NDArray[np.bool_], *, skipna: bool = True): ...
def cummax(values: np.ndarray, mask: npt.NDArray[np.bool_], *, skipna: bool = True): ...
