import numpy as np
import pyarrow as pa
from pandas.core.interchange.dataframe_protocol import Buffer as Buffer, DlpackDeviceType as DlpackDeviceType
from typing import Any

class PandasBuffer(Buffer):
    def __init__(self, x: np.ndarray, allow_copy: bool = True) -> None: ...
    @property
    def bufsize(self) -> int: ...
    @property
    def ptr(self) -> int: ...
    def __dlpack__(self) -> Any: ...
    def __dlpack_device__(self) -> tuple[DlpackDeviceType, int | None]: ...

class PandasBufferPyarrow(Buffer):
    def __init__(self, buffer: pa.Buffer, *, length: int) -> None: ...
    @property
    def bufsize(self) -> int: ...
    @property
    def ptr(self) -> int: ...
    def __dlpack__(self) -> Any: ...
    def __dlpack_device__(self) -> tuple[DlpackDeviceType, int | None]: ...
