from _typeshed import Incomplete
from numba import types
from numba.core.datamodel import models
from pandas._libs import lib as lib
from pandas.core.indexes.base import Index as Index
from pandas.core.internals import SingleBlockManager as SingleBlockManager
from pandas.core.series import Series as Series

def set_numba_data(index: Index): ...

class IndexType(types.Type):
    pyclass: Incomplete
    dtype: Incomplete
    layout: Incomplete
    def __init__(self, dtype, layout, pyclass: any) -> None: ...
    @property
    def key(self): ...
    @property
    def as_array(self): ...
    def copy(self, dtype: Incomplete | None = None, ndim: int = 1, layout: Incomplete | None = None): ...

class SeriesType(types.Type):
    dtype: Incomplete
    index: Incomplete
    values: Incomplete
    namety: Incomplete
    def __init__(self, dtype, index, namety) -> None: ...
    @property
    def key(self): ...
    @property
    def as_array(self): ...
    def copy(self, dtype: Incomplete | None = None, ndim: int = 1, layout: str = 'C'): ...

def typeof_index(val, c): ...
def typeof_series(val, c): ...
def type_series_constructor(context): ...
def type_index_constructor(context): ...

class IndexModel(models.StructModel):
    def __init__(self, dmm, fe_type) -> None: ...

class SeriesModel(models.StructModel):
    def __init__(self, dmm, fe_type) -> None: ...

def pdseries_constructor(context, builder, sig, args): ...
def pdseries_constructor_with_name(context, builder, sig, args): ...
def index_constructor_2arg(context, builder, sig, args): ...
def index_constructor_2arg_parent(context, builder, sig, args): ...
def index_constructor_1arg(context, builder, sig, args): ...
def maybe_cast_str(x) -> None: ...
def maybe_cast_str_impl(x): ...
def unbox_index(typ, obj, c): ...
def unbox_series(typ, obj, c): ...
def box_index(typ, val, c): ...
def box_series(typ, val, c): ...
def generate_series_reduction(ser_reduction, ser_method): ...
def generate_series_binop(binop): ...

series_reductions: Incomplete
series_binops: Incomplete

def index_get_loc(index, item): ...
def series_indexing(series, item): ...
def index_indexing(index, idx): ...

class IlocType(types.Type):
    obj_type: Incomplete
    def __init__(self, obj_type) -> None: ...
    @property
    def key(self): ...

def typeof_iloc(val, c): ...
def type_iloc_constructor(context): ...
def iloc_constructor(context, builder, sig, args): ...

class ILocModel(models.StructModel):
    def __init__(self, dmm, fe_type) -> None: ...

def series_iloc(series): ...
def iloc_getitem(iloc_indexer, i): ...
