import numpy as np
from _typeshed import Incomplete
from pandas import Series as Series
from pandas._config import get_option as get_option
from pandas._libs import lib as lib
from pandas._libs.tslibs import NaT as NaT, iNaT as iNaT
from pandas._typing import ArrayLike as ArrayLike, DtypeObj as DtypeObj, NDFrame as NDFrame, NDFrameT as NDFrameT, Scalar as Scalar, npt as npt
from pandas.core.dtypes.common import DT64NS_DTYPE as DT64NS_DTYPE, TD64NS_DTYPE as TD64NS_DTYPE, ensure_object as ensure_object, is_scalar as is_scalar, is_string_or_object_np_dtype as is_string_or_object_np_dtype
from pandas.core.dtypes.dtypes import CategoricalDtype as CategoricalDtype, DatetimeTZDtype as DatetimeTZDtype, ExtensionDtype as ExtensionDtype, IntervalDtype as IntervalDtype, PeriodDtype as PeriodDtype
from pandas.core.dtypes.generic import ABCDataFrame as ABCDataFrame, ABCExtensionArray as ABCExtensionArray, ABCIndex as ABCIndex, ABCMultiIndex as ABCMultiIndex, ABCSeries as ABCSeries
from pandas.core.dtypes.inference import is_list_like as is_list_like
from pandas.core.indexes.base import Index as Index
from re import Pattern
from typing import overload

isposinf_scalar: Incomplete
isneginf_scalar: Incomplete
nan_checker: Incomplete
INF_AS_NA: bool

@overload
def isna(obj: Scalar | Pattern) -> bool: ...
@overload
def isna(obj: ArrayLike | Index | list) -> npt.NDArray[np.bool_]: ...
@overload
def isna(obj: NDFrameT) -> NDFrameT: ...
@overload
def isna(obj: NDFrameT | ArrayLike | Index | list) -> NDFrameT | npt.NDArray[np.bool_]: ...
@overload
def isna(obj: object) -> bool | npt.NDArray[np.bool_] | NDFrame: ...
isnull = isna

@overload
def notna(obj: Scalar) -> bool: ...
@overload
def notna(obj: ArrayLike | Index | list) -> npt.NDArray[np.bool_]: ...
@overload
def notna(obj: NDFrameT) -> NDFrameT: ...
@overload
def notna(obj: NDFrameT | ArrayLike | Index | list) -> NDFrameT | npt.NDArray[np.bool_]: ...
@overload
def notna(obj: object) -> bool | npt.NDArray[np.bool_] | NDFrame: ...
notnull = notna

def array_equivalent(left, right, strict_nan: bool = False, dtype_equal: bool = False) -> bool: ...
def array_equals(left: ArrayLike, right: ArrayLike) -> bool: ...
def infer_fill_value(val): ...
def construct_1d_array_from_inferred_fill_value(value: object, length: int) -> ArrayLike: ...
def maybe_fill(arr: np.ndarray) -> np.ndarray: ...
def na_value_for_dtype(dtype: DtypeObj, compat: bool = True): ...
def remove_na_arraylike(arr: Series | Index | np.ndarray): ...
def is_valid_na_for_dtype(obj, dtype: DtypeObj) -> bool: ...
def isna_all(arr: ArrayLike) -> bool: ...
