from _typeshed import Incomplete
from collections.abc import Iterable
from pandas import MultiIndex as MultiIndex, option_context as option_context
from pandas._config import get_option as get_option
from pandas._libs import lib as lib
from pandas.io.common import is_url as is_url
from pandas.io.formats.format import DataFrameFormatter as DataFrameFormatter, get_level_lengths as get_level_lengths
from pandas.io.formats.printing import pprint_thing as pprint_thing
from typing import Any, Final

class HTMLFormatter:
    indent_delta: Final[int]
    fmt: Incomplete
    classes: Incomplete
    frame: Incomplete
    columns: Incomplete
    elements: list[str]
    bold_rows: Incomplete
    escape: Incomplete
    show_dimensions: Incomplete
    border: Incomplete
    table_id: Incomplete
    render_links: Incomplete
    col_space: Incomplete
    def __init__(self, formatter: DataFrameFormatter, classes: str | list[str] | tuple[str, ...] | None = None, border: int | bool | None = None, table_id: str | None = None, render_links: bool = False) -> None: ...
    def to_string(self) -> str: ...
    def render(self) -> list[str]: ...
    @property
    def should_show_dimensions(self) -> bool: ...
    @property
    def show_row_idx_names(self) -> bool: ...
    @property
    def show_col_idx_names(self) -> bool: ...
    @property
    def row_levels(self) -> int: ...
    @property
    def is_truncated(self) -> bool: ...
    @property
    def ncols(self) -> int: ...
    def write(self, s: Any, indent: int = 0) -> None: ...
    def write_th(self, s: Any, header: bool = False, indent: int = 0, tags: str | None = None) -> None: ...
    def write_td(self, s: Any, indent: int = 0, tags: str | None = None) -> None: ...
    def write_tr(self, line: Iterable, indent: int = 0, indent_delta: int = 0, header: bool = False, align: str | None = None, tags: dict[int, str] | None = None, nindex_levels: int = 0) -> None: ...

class NotebookFormatter(HTMLFormatter):
    def write_style(self) -> None: ...
    def render(self) -> list[str]: ...
