from pandas.core.generic import NDFrame as NDFrame

class Flags:
    def __init__(self, obj: NDFrame, *, allows_duplicate_labels: bool) -> None: ...
    @property
    def allows_duplicate_labels(self) -> bool: ...
    @allows_duplicate_labels.setter
    def allows_duplicate_labels(self, value: bool) -> None: ...
    def __getitem__(self, key: str): ...
    def __setitem__(self, key: str, value) -> None: ...
    def __eq__(self, other) -> bool: ...
