from collections.abc import Generator
from pandas._config.config import options as options

def set_locale(new_locale: str | tuple[str, str], lc_var: int = ...) -> Generator[str | tuple[str, str], None, None]: ...
def can_set_locale(lc: str, lc_var: int = ...) -> bool: ...
def get_locales(prefix: str | None = None, normalize: bool = True) -> list[str]: ...
