def dgelsd(*args, **kwargs): ...
def dgeqrf(*args, **kwargs): ...
def dorgqr(*args, **kwargs): ...
def xerbla(*args, **kwargs): ...
def zgelsd(*args, **kwargs): ...
def zgeqrf(*args, **kwargs): ...
def zungqr(*args, **kwargs): ...
