from _typeshed import Incomplete

__all__ = ['fftshift', 'ifftshift', 'fftfreq', 'rfftfreq']

def fftshift(x, axes: Incomplete | None = None): ...
def ifftshift(x, axes: Incomplete | None = None): ...
def fftfreq(n, d: float = 1.0, device: Incomplete | None = None): ...
def rfftfreq(n, d: float = 1.0, device: Incomplete | None = None): ...
