from _typeshed import Incomplete

__all__ = ['fft', 'ifft', 'rfft', 'irfft', 'hfft', 'ihfft', 'rfftn', 'irfftn', 'rfft2', 'irfft2', 'fft2', 'ifft2', 'fftn', 'ifftn']

def fft(a, n: Incomplete | None = None, axis: int = -1, norm: Incomplete | None = None, out: Incomplete | None = None): ...
def ifft(a, n: Incomplete | None = None, axis: int = -1, norm: Incomplete | None = None, out: Incomplete | None = None): ...
def rfft(a, n: Incomplete | None = None, axis: int = -1, norm: Incomplete | None = None, out: Incomplete | None = None): ...
def irfft(a, n: Incomplete | None = None, axis: int = -1, norm: Incomplete | None = None, out: Incomplete | None = None): ...
def hfft(a, n: Incomplete | None = None, axis: int = -1, norm: Incomplete | None = None, out: Incomplete | None = None): ...
def ihfft(a, n: Incomplete | None = None, axis: int = -1, norm: Incomplete | None = None, out: Incomplete | None = None): ...
def fftn(a, s: Incomplete | None = None, axes: Incomplete | None = None, norm: Incomplete | None = None, out: Incomplete | None = None): ...
def ifftn(a, s: Incomplete | None = None, axes: Incomplete | None = None, norm: Incomplete | None = None, out: Incomplete | None = None): ...
def fft2(a, s: Incomplete | None = None, axes=(-2, -1), norm: Incomplete | None = None, out: Incomplete | None = None): ...
def ifft2(a, s: Incomplete | None = None, axes=(-2, -1), norm: Incomplete | None = None, out: Incomplete | None = None): ...
def rfftn(a, s: Incomplete | None = None, axes: Incomplete | None = None, norm: Incomplete | None = None, out: Incomplete | None = None): ...
def rfft2(a, s: Incomplete | None = None, axes=(-2, -1), norm: Incomplete | None = None, out: Incomplete | None = None): ...
def irfftn(a, s: Incomplete | None = None, axes: Incomplete | None = None, norm: Incomplete | None = None, out: Incomplete | None = None): ...
def irfft2(a, s: Incomplete | None = None, axes=(-2, -1), norm: Incomplete | None = None, out: Incomplete | None = None): ...
