from _typeshed import Incomplete
from numpy._core import bool as bool, complex128 as complex128, complex64 as complex64, dtype as dtype, float32 as float32, float64 as float64, int16 as int16, int32 as int32, int64 as int64, int8 as int8, intp as intp, uint16 as uint16, uint32 as uint32, uint64 as uint64, uint8 as uint8

class __array_namespace_info__:
    __module__: str
    def capabilities(self): ...
    def default_device(self): ...
    def default_dtypes(self, *, device: Incomplete | None = None): ...
    def dtypes(self, *, device: Incomplete | None = None, kind: Incomplete | None = None): ...
    def devices(self): ...
