from _typeshed import Incomplete

__all__ = ['ComplexWarning', 'VisibleDeprecationWarning', 'ModuleDeprecationWarning', 'TooHardError', 'AxisError', 'DTypePromotionError']

class ComplexWarning(RuntimeWarning): ...
class ModuleDeprecationWarning(DeprecationWarning): ...
class VisibleDeprecationWarning(UserWarning): ...
class RankWarning(RuntimeWarning): ...
class TooHardError(RuntimeError): ...

class AxisError(ValueError, IndexError):
    axis: Incomplete
    ndim: Incomplete
    def __init__(self, axis, ndim: Incomplete | None = None, msg_prefix: Incomplete | None = None) -> None: ...

class DTypePromotionError(TypeError): ...
