from numpy import *
from _typeshed import Incomplete
from numpy.matrixlib.defmatrix import asmatrix as asmatrix, matrix as matrix

__all__ = ['divmod', 'require', 'place', 'ufunc', 'heaviside', 'datetime64', 'argpartition', 'mgrid', 'convolve', 'unique_values', 'strings', 'isfortran', 'rec', 'uint8', 'hanning', 'indices', 'nextafter', 'nan', 'interp', 'split', 'arccos', 'array_split', 'pad', 'complex64', 'number', 'unravel_index', 'float32', 'e', 'real', 'cbrt', 'true_divide', 'array2string', 'diag', 'astype', 'vecdot', 'atleast_2d', 'iscomplexobj', 'linalg', 'arccosh', 'einsum', 'fromstring', 'arcsin', 'piecewise', 'flatnonzero', 'vander', 'bitwise_invert', 'ndenumerate', 'bitwise_not', 'ediff1d', 'float16', 'acosh', 'long', 'repeat', 'full_like', 'loadtxt', 'nancumprod', 'squeeze', 'invert', 'in1d', 'blackman', 'lexsort', 'vecmat', 'acos', 'r_', 'ushort', 'fromfile', 'conjugate', 'floating', 'sinc', 'trapz', 'conj', 'datetime_data', 'isfinite', 'sinh', 'tril_indices', 'imag', 'fmod', 'geomspace', 'vectorize', 'arcsinh', 'fabs', 'log10', 'expand_dims', 'einsum_path', 'arctan2', 'remainder', 'int32', 'mod', 'True_', 'concatenate', 'finfo', 'char', 'kaiser', 'savez', 'empty_like', 'std', 'pi', 'logspace', 'asarray', 'rollaxis', 'sign', 'bytes_', 'intp', 'iinfo', 'radians', 'apply_over_axes', 'prod', 'ndindex', 'gradient', 'bool', 'uint16', 'iterable', 'hstack', 'core', 'around', 'bartlett', 'c_', 'asin', 'tri', 'extract', 'log1p', 'quantile', 'isreal', 'int16', 'square', 'amin', 'mean', 'savetxt', '__array_namespace_info__', 'is_busday', 'atanh', 'isneginf', 'zeros', 'object_', 'vdot', 'setbufsize', 'clongdouble', 'stack', 'exceptions', 'spacing', 'longdouble', 'argsort', 'emath', 'argmax', 'flipud', 'fromregex', 'digitize', 'trapezoid', 'asanyarray', 'datetime_as_string', 'fromiter', 'bincount', 'trace', 'frexp', 'polydiv', 'timedelta64', 'atan', 'isinf', 'integer', 'average', 'diagflat', 'size', 'logical_not', 'single', 'fliplr', 'polyint', 'empty', 'nanstd', 'histogram_bin_edges', 'ma', 'corrcoef', 'busday_offset', 'info', 'inf', 'float64', 'concat', 'isin', 'nonzero', 's_', 'isnan', 'asfortranarray', 'unstack', 'iscomplex', 'nanargmin', 'asarray_chkfinite', 'moveaxis', 'format_float_positional', 'partition', 'half', 'short', 'row_stack', 'isrealobj', 'sum', 'not_equal', 'intc', 'broadcast_arrays', 'bitwise_right_shift', 'dtype', 'take_along_axis', 'packbits', 'exp', 'str_', 'insert', 'eye', 'get_printoptions', 'ogrid', 'transpose', 'triu_indices_from', 'identity', 'csingle', 'meshgrid', '__version__', 'flatiter', 'logaddexp', 'put', 'cos', 'nanmin', 'choose', 'cov', 'power', 'polynomial', 'can_cast', 'void', 'bitwise_count', 'uint', 'recarray', 'from_dlpack', 'diff', 'broadcast_shapes', 'uintc', 'lib', 'compress', 'shape', 'vstack', 'newaxis', 'argmin', 'union1d', 'little_endian', 'equal', 'nanprod', 'nanpercentile', 'seterr', 'round', 'copy', 'greater_equal', 'add', 'complexfloating', 'seterrcall', 'typing', 'min', 'ldexp', 'exp2', 'atleast_3d', 'kron', 'record', 'genfromtxt', 'logical_or', 'rad2deg', 'False_', 'bmat', 'log2', 'polyfit', 'ulong', 'geterrcall', 'expm1', 'sin', 'all', 'rot90', 'ulonglong', 'ravel', 'base_repr', 'tril_indices_from', 'typename', 'var', 'right_shift', 'poly', 'geterr', 'array_repr', 'save', 'append', 'inner', 'rint', 'left_shift', 'clip', 'less', 'linspace', 'cumprod', 'modf', 'issubdtype', 'get_include', 'load', 'float_power', 'column_stack', 'roots', 'uint64', 'negative', 'positive', 'gcd', 'arctan', 'longlong', 'polyadd', 'where', 'swapaxes', 'polyval', 'fmax', 'roll', 'format_float_scientific', 'abs', 'isdtype', 'select', 'generic', 'cdouble', 'unpackbits', 'sqrt', 'pow', 'getbufsize', 'zeros_like', 'copysign', 'nansum', 'median', 'triu', 'tile', 'divide', 'euler_gamma', 'permute_dims', 'broadcast', 'diag_indices', 'ScalarType', 'flexible', 'nanmax', 'ix_', 'nanmedian', 'savez_compressed', 'put_along_axis', 'polymul', 'real_if_close', 'dtypes', 'block', 'matrix_transpose', 'reciprocal', 'array_equal', 'absolute', 'bool_', 'isnat', 'byte', 'ones', 'atan2', 'isposinf', 'degrees', 'shares_memory', 'fft', 'bitwise_or', 'putmask', 'minimum', 'percentile', 'tanh', 'nancumsum', 'searchsorted', 'trim_zeros', 'histogramdd', 'amax', 'unique', 'unique_all', 'setdiff1d', 'cumsum', 'count_nonzero', 'cumulative_prod', 'typecodes', 'angle', 'nested_iters', 'min_scalar_type', 'f2py', 'setxor1d', 'max', 'reshape', 'matvec', 'correlate', 'signbit', 'matrix', 'i0', 'less_equal', 'sort_complex', 'polysub', 'logaddexp2', 'take', 'hypot', 'busday_count', 'unwrap', 'outer', 'cross', 'subtract', 'complex128', 'tensordot', 'argwhere', 'vsplit', 'fix', 'nanvar', 'hsplit', 'may_share_memory', 'int_', 'common_type', 'apply_along_axis', 'maximum', 'test', 'int8', 'mask_indices', 'nan_to_num', 'triu_indices', 'ptp', 'unique_counts', 'inexact', 'nditer', 'double', 'show_runtime', 'bitwise_and', 'floor', 'isclose', 'ndarray', 'dot', 'matmul', 'ones_like', 'frombuffer', 'dstack', 'logical_and', 'int64', 'cumulative_sum', 'dsplit', 'tril', 'random', 'poly1d', 'set_printoptions', 'unsignedinteger', 'uint32', 'sort', 'bitwise_xor', 'copyto', 'log', 'polyder', 'any', 'array_str', 'fmin', 'multiply', 'atleast_1d', 'greater', 'diagonal', 'mintypecode', 'cosh', 'index_exp', 'uintp', 'unique_inverse', 'ndim', 'arange', 'ascontiguousarray', 'fill_diagonal', 'show_config', 'broadcast_to', 'printoptions', 'bitwise_left_shift', 'arctanh', 'signedinteger', 'asinh', 'array', 'fromfunction', 'nanargmax', 'memmap', 'lcm', 'ubyte', 'trunc', 'histogram2d', 'nanmean', 'histogram', 'floor_divide', 'ctypeslib', 'promote_types', 'intersect1d', 'full', 'hamming', 'resize', 'allclose', 'deg2rad', 'ravel_multi_index', 'busdaycalendar', 'binary_repr', 'array_equiv', 'isscalar', 'sctypeDict', 'asmatrix', 'logical_xor', 'tan', 'nanquantile', 'diag_indices_from', 'ceil', 'frompyfunc', 'flip', 'result_type', 'delete', 'errstate', 'character', 'testing', 'rand', 'randn', 'repmat']

__version__: Incomplete

def empty(shape, dtype: Incomplete | None = None, order: str = 'C'): ...
def ones(shape, dtype: Incomplete | None = None, order: str = 'C'): ...
def zeros(shape, dtype: Incomplete | None = None, order: str = 'C'): ...
def identity(n, dtype: Incomplete | None = None): ...
def eye(n, M: Incomplete | None = None, k: int = 0, dtype=..., order: str = 'C'): ...
def rand(*args): ...
def randn(*args): ...
def repmat(a, m, n): ...

# Names in __all__ with no definition:
#   False_
#   ScalarType
#   True_
#   __array_namespace_info__
#   abs
#   absolute
#   acos
#   acosh
#   add
#   all
#   allclose
#   amax
#   amin
#   angle
#   any
#   append
#   apply_along_axis
#   apply_over_axes
#   arange
#   arccos
#   arccosh
#   arcsin
#   arcsinh
#   arctan
#   arctan2
#   arctanh
#   argmax
#   argmin
#   argpartition
#   argsort
#   argwhere
#   around
#   array
#   array2string
#   array_equal
#   array_equiv
#   array_repr
#   array_split
#   array_str
#   asanyarray
#   asarray
#   asarray_chkfinite
#   ascontiguousarray
#   asfortranarray
#   asin
#   asinh
#   astype
#   atan
#   atan2
#   atanh
#   atleast_1d
#   atleast_2d
#   atleast_3d
#   average
#   bartlett
#   base_repr
#   binary_repr
#   bincount
#   bitwise_and
#   bitwise_count
#   bitwise_invert
#   bitwise_left_shift
#   bitwise_not
#   bitwise_or
#   bitwise_right_shift
#   bitwise_xor
#   blackman
#   block
#   bmat
#   bool
#   bool_
#   broadcast
#   broadcast_arrays
#   broadcast_shapes
#   broadcast_to
#   busday_count
#   busday_offset
#   busdaycalendar
#   byte
#   bytes_
#   c_
#   can_cast
#   cbrt
#   cdouble
#   ceil
#   char
#   character
#   choose
#   clip
#   clongdouble
#   column_stack
#   common_type
#   complex128
#   complex64
#   complexfloating
#   compress
#   concat
#   concatenate
#   conj
#   conjugate
#   convolve
#   copy
#   copysign
#   copyto
#   core
#   corrcoef
#   correlate
#   cos
#   cosh
#   count_nonzero
#   cov
#   cross
#   csingle
#   ctypeslib
#   cumprod
#   cumsum
#   cumulative_prod
#   cumulative_sum
#   datetime64
#   datetime_as_string
#   datetime_data
#   deg2rad
#   degrees
#   delete
#   diag
#   diag_indices
#   diag_indices_from
#   diagflat
#   diagonal
#   diff
#   digitize
#   divide
#   divmod
#   dot
#   double
#   dsplit
#   dstack
#   dtype
#   dtypes
#   e
#   ediff1d
#   einsum
#   einsum_path
#   emath
#   empty_like
#   equal
#   errstate
#   euler_gamma
#   exceptions
#   exp
#   exp2
#   expand_dims
#   expm1
#   extract
#   f2py
#   fabs
#   fft
#   fill_diagonal
#   finfo
#   fix
#   flatiter
#   flatnonzero
#   flexible
#   flip
#   fliplr
#   flipud
#   float16
#   float32
#   float64
#   float_power
#   floating
#   floor
#   floor_divide
#   fmax
#   fmin
#   fmod
#   format_float_positional
#   format_float_scientific
#   frexp
#   from_dlpack
#   frombuffer
#   fromfile
#   fromfunction
#   fromiter
#   frompyfunc
#   fromregex
#   fromstring
#   full
#   full_like
#   gcd
#   generic
#   genfromtxt
#   geomspace
#   get_include
#   get_printoptions
#   getbufsize
#   geterr
#   geterrcall
#   gradient
#   greater
#   greater_equal
#   half
#   hamming
#   hanning
#   heaviside
#   histogram
#   histogram2d
#   histogram_bin_edges
#   histogramdd
#   hsplit
#   hstack
#   hypot
#   i0
#   iinfo
#   imag
#   in1d
#   index_exp
#   indices
#   inexact
#   inf
#   info
#   inner
#   insert
#   int16
#   int32
#   int64
#   int8
#   int_
#   intc
#   integer
#   interp
#   intersect1d
#   intp
#   invert
#   is_busday
#   isclose
#   iscomplex
#   iscomplexobj
#   isdtype
#   isfinite
#   isfortran
#   isin
#   isinf
#   isnan
#   isnat
#   isneginf
#   isposinf
#   isreal
#   isrealobj
#   isscalar
#   issubdtype
#   iterable
#   ix_
#   kaiser
#   kron
#   lcm
#   ldexp
#   left_shift
#   less
#   less_equal
#   lexsort
#   lib
#   linalg
#   linspace
#   little_endian
#   load
#   loadtxt
#   log
#   log10
#   log1p
#   log2
#   logaddexp
#   logaddexp2
#   logical_and
#   logical_not
#   logical_or
#   logical_xor
#   logspace
#   long
#   longdouble
#   longlong
#   ma
#   mask_indices
#   matmul
#   matrix_transpose
#   matvec
#   max
#   maximum
#   may_share_memory
#   mean
#   median
#   memmap
#   meshgrid
#   mgrid
#   min
#   min_scalar_type
#   minimum
#   mintypecode
#   mod
#   modf
#   moveaxis
#   multiply
#   nan
#   nan_to_num
#   nanargmax
#   nanargmin
#   nancumprod
#   nancumsum
#   nanmax
#   nanmean
#   nanmedian
#   nanmin
#   nanpercentile
#   nanprod
#   nanquantile
#   nanstd
#   nansum
#   nanvar
#   ndarray
#   ndenumerate
#   ndim
#   ndindex
#   nditer
#   negative
#   nested_iters
#   newaxis
#   nextafter
#   nonzero
#   not_equal
#   number
#   object_
#   ogrid
#   ones_like
#   outer
#   packbits
#   pad
#   partition
#   percentile
#   permute_dims
#   pi
#   piecewise
#   place
#   poly
#   poly1d
#   polyadd
#   polyder
#   polydiv
#   polyfit
#   polyint
#   polymul
#   polynomial
#   polysub
#   polyval
#   positive
#   pow
#   power
#   printoptions
#   prod
#   promote_types
#   ptp
#   put
#   put_along_axis
#   putmask
#   quantile
#   r_
#   rad2deg
#   radians
#   random
#   ravel
#   ravel_multi_index
#   real
#   real_if_close
#   rec
#   recarray
#   reciprocal
#   record
#   remainder
#   repeat
#   require
#   reshape
#   resize
#   result_type
#   right_shift
#   rint
#   roll
#   rollaxis
#   roots
#   rot90
#   round
#   row_stack
#   s_
#   save
#   savetxt
#   savez
#   savez_compressed
#   sctypeDict
#   searchsorted
#   select
#   set_printoptions
#   setbufsize
#   setdiff1d
#   seterr
#   seterrcall
#   setxor1d
#   shape
#   shares_memory
#   short
#   show_config
#   show_runtime
#   sign
#   signbit
#   signedinteger
#   sin
#   sinc
#   single
#   sinh
#   size
#   sort
#   sort_complex
#   spacing
#   split
#   sqrt
#   square
#   squeeze
#   stack
#   std
#   str_
#   strings
#   subtract
#   sum
#   swapaxes
#   take
#   take_along_axis
#   tan
#   tanh
#   tensordot
#   test
#   testing
#   tile
#   timedelta64
#   trace
#   transpose
#   trapezoid
#   trapz
#   tri
#   tril
#   tril_indices
#   tril_indices_from
#   trim_zeros
#   triu
#   triu_indices
#   triu_indices_from
#   true_divide
#   trunc
#   typecodes
#   typename
#   typing
#   ubyte
#   ufunc
#   uint
#   uint16
#   uint32
#   uint64
#   uint8
#   uintc
#   uintp
#   ulong
#   ulonglong
#   union1d
#   unique
#   unique_all
#   unique_counts
#   unique_inverse
#   unique_values
#   unpackbits
#   unravel_index
#   unsignedinteger
#   unstack
#   unwrap
#   ushort
#   vander
#   var
#   vdot
#   vecdot
#   vecmat
#   vectorize
#   void
#   vsplit
#   vstack
#   where
#   zeros_like
