from _typeshed import Incomplete
from pandas._config.config import OptionError as OptionError
from pandas._libs.tslibs import OutOfBoundsDatetime as OutOfBoundsDatetime, OutOfBoundsTimedelta as OutOfBoundsTimedelta
from pandas.util.version import InvalidVersion as InvalidVersion

__all__ = ['AbstractMethodError', 'AttributeConflictWarning', 'CategoricalConversionWarning', 'ClosedFileError', 'CSSWarning', 'DatabaseError', 'DataError', 'DtypeWarning', 'DuplicateLabelError', 'EmptyDataError', 'IncompatibilityWarning', 'IntCastingNaNError', 'InvalidColumnName', 'InvalidComparison', 'InvalidIndexError', 'InvalidVersion', 'IndexingError', 'LossySetitemError', 'MergeError', 'NoBufferPresent', 'NullFrequencyError', 'NumbaUtilError', 'NumExprClobberingError', 'OptionError', 'OutOfBoundsDatetime', 'OutOfBoundsTimedelta', 'ParserError', 'ParserWarning', 'PerformanceWarning', 'PossibleDataLossError', 'PossiblePrecisionLoss', 'PyperclipException', 'PyperclipWindowsException', 'SettingWithCopyError', 'SettingWithCopyWarning', 'SpecificationError', 'UndefinedVariableError', 'UnsortedIndexError', 'UnsupportedFunctionCall', 'ValueLabelTypeMismatch']

class IntCastingNaNError(ValueError): ...
class NullFrequencyError(ValueError): ...
class PerformanceWarning(Warning): ...
class UnsupportedFunctionCall(ValueError): ...
class UnsortedIndexError(KeyError): ...
class ParserError(ValueError): ...
class DtypeWarning(Warning): ...
class EmptyDataError(ValueError): ...
class ParserWarning(Warning): ...
class MergeError(ValueError): ...

class AbstractMethodError(NotImplementedError):
    methodtype: Incomplete
    class_instance: Incomplete
    def __init__(self, class_instance, methodtype: str = 'method') -> None: ...

class NumbaUtilError(Exception): ...
class DuplicateLabelError(ValueError): ...
class InvalidIndexError(Exception): ...
class DataError(Exception): ...
class SpecificationError(Exception): ...
class SettingWithCopyError(ValueError): ...
class SettingWithCopyWarning(Warning): ...
class ChainedAssignmentError(Warning): ...
class NumExprClobberingError(NameError): ...

class UndefinedVariableError(NameError):
    def __init__(self, name: str, is_local: bool | None = None) -> None: ...

class IndexingError(Exception): ...
class PyperclipException(RuntimeError): ...

class PyperclipWindowsException(PyperclipException):
    def __init__(self, message: str) -> None: ...

class CSSWarning(UserWarning): ...
class PossibleDataLossError(Exception): ...
class ClosedFileError(Exception): ...
class IncompatibilityWarning(Warning): ...
class AttributeConflictWarning(Warning): ...
class DatabaseError(OSError): ...
class PossiblePrecisionLoss(Warning): ...
class ValueLabelTypeMismatch(Warning): ...
class InvalidColumnName(Warning): ...
class CategoricalConversionWarning(Warning): ...
class LossySetitemError(Exception): ...
class NoBufferPresent(Exception): ...
class InvalidComparison(Exception): ...
