import abc
from _typeshed import Incomplete

__all__ = ['ABCPolyBase']

class ABCPolyBase(abc.ABC, metaclass=abc.ABCMeta):
    __hash__: Incomplete
    __array_ufunc__: Incomplete
    maxpower: int
    @property
    def symbol(self): ...
    @property
    @abc.abstractmethod
    def domain(self): ...
    @property
    @abc.abstractmethod
    def window(self): ...
    @property
    @abc.abstractmethod
    def basis_name(self): ...
    def has_samecoef(self, other): ...
    def has_samedomain(self, other): ...
    def has_samewindow(self, other): ...
    def has_sametype(self, other): ...
    coef: Incomplete
    def __init__(self, coef, domain: Incomplete | None = None, window: Incomplete | None = None, symbol: str = 'x') -> None: ...
    def __format__(self, fmt_str) -> str: ...
    def __call__(self, arg): ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __neg__(self): ...
    def __pos__(self): ...
    def __add__(self, other): ...
    def __sub__(self, other): ...
    def __mul__(self, other): ...
    def __truediv__(self, other): ...
    def __floordiv__(self, other): ...
    def __mod__(self, other): ...
    def __divmod__(self, other): ...
    def __pow__(self, other): ...
    def __radd__(self, other): ...
    def __rsub__(self, other): ...
    def __rmul__(self, other): ...
    def __rdiv__(self, other): ...
    def __rtruediv__(self, other): ...
    def __rfloordiv__(self, other): ...
    def __rmod__(self, other): ...
    def __rdivmod__(self, other): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def copy(self): ...
    def degree(self): ...
    def cutdeg(self, deg): ...
    def trim(self, tol: int = 0): ...
    def truncate(self, size): ...
    def convert(self, domain: Incomplete | None = None, kind: Incomplete | None = None, window: Incomplete | None = None): ...
    def mapparms(self): ...
    def integ(self, m: int = 1, k=[], lbnd: Incomplete | None = None): ...
    def deriv(self, m: int = 1): ...
    def roots(self): ...
    def linspace(self, n: int = 100, domain: Incomplete | None = None): ...
    @classmethod
    def fit(cls, x, y, deg, domain: Incomplete | None = None, rcond: Incomplete | None = None, full: bool = False, w: Incomplete | None = None, window: Incomplete | None = None, symbol: str = 'x'): ...
    @classmethod
    def fromroots(cls, roots, domain=[], window: Incomplete | None = None, symbol: str = 'x'): ...
    @classmethod
    def identity(cls, domain: Incomplete | None = None, window: Incomplete | None = None, symbol: str = 'x'): ...
    @classmethod
    def basis(cls, deg, domain: Incomplete | None = None, window: Incomplete | None = None, symbol: str = 'x'): ...
    @classmethod
    def cast(cls, series, domain: Incomplete | None = None, window: Incomplete | None = None): ...
