from _typeshed import Incomplete
from collections.abc import Generator
from pandas import set_option as set_option
from pandas._config import using_copy_on_write as using_copy_on_write
from pandas._typing import BaseBuffer as BaseBuffer, CompressionOptions as CompressionOptions, FilePath as FilePath
from pandas.compat import PYPY as PYPY
from pandas.errors import ChainedAssignmentError as ChainedAssignmentError
from pandas.io.common import get_handle as get_handle
from typing import Any, IO

def decompress_file(path: FilePath | BaseBuffer, compression: CompressionOptions) -> Generator[IO[bytes], None, None]: ...
def set_timezone(tz: str) -> Generator[None, None, None]: ...
def ensure_clean(filename: Incomplete | None = None, return_filelike: bool = False, **kwargs: Any) -> Generator[Any, None, None]: ...
def with_csv_dialect(name: str, **kwargs) -> Generator[None, None, None]: ...
def use_numexpr(use, min_elements: Incomplete | None = None) -> Generator[None, None, None]: ...
def raises_chained_assignment_error(warn: bool = True, extra_warnings=(), extra_match=()): ...
def assert_cow_warning(warn: bool = True, match: Incomplete | None = None, **kwargs): ...
