from pandas.compat._optional import import_optional_dependency as import_optional_dependency
from pandas.errors import NumbaUtilError as NumbaUtilError
from typing import Callable

GLOBAL_USE_NUMBA: bool

def maybe_use_numba(engine: str | None) -> bool: ...
def set_use_numba(enable: bool = False) -> None: ...
def get_jit_arguments(engine_kwargs: dict[str, bool] | None = None, kwargs: dict | None = None) -> dict[str, bool]: ...
def jit_user_function(func: Callable) -> Callable: ...
