import pandas as pd
from . import cache as cache, utils as utils
from .data import YfData as YfData
from .exceptions import YFEarningsDateMissing as YFEarningsDateMissing, YFRateLimitError as YFRateLimitError
from .scrapers.analysis import Analysis as Analysis
from .scrapers.fundamentals import Fundamentals as Fundamentals
from .scrapers.funds import FundsData as FundsData
from .scrapers.history import PriceHistory as PriceHistory
from .scrapers.holders import Holders as Holders
from .scrapers.quote import FastInfo as FastInfo, Quote as Quote
from _typeshed import Incomplete

class TickerBase:
    ticker: Incomplete
    proxy: Incomplete
    session: Incomplete
    def __init__(self, ticker, session: Incomplete | None = None, proxy: Incomplete | None = None) -> None: ...
    def history(self, *args, **kwargs) -> pd.DataFrame: ...
    def get_recommendations(self, proxy: Incomplete | None = None, as_dict: bool = False): ...
    def get_recommendations_summary(self, proxy: Incomplete | None = None, as_dict: bool = False): ...
    def get_upgrades_downgrades(self, proxy: Incomplete | None = None, as_dict: bool = False): ...
    def get_calendar(self, proxy: Incomplete | None = None) -> dict: ...
    def get_sec_filings(self, proxy: Incomplete | None = None) -> dict: ...
    def get_major_holders(self, proxy: Incomplete | None = None, as_dict: bool = False): ...
    def get_institutional_holders(self, proxy: Incomplete | None = None, as_dict: bool = False): ...
    def get_mutualfund_holders(self, proxy: Incomplete | None = None, as_dict: bool = False): ...
    def get_insider_purchases(self, proxy: Incomplete | None = None, as_dict: bool = False): ...
    def get_insider_transactions(self, proxy: Incomplete | None = None, as_dict: bool = False): ...
    def get_insider_roster_holders(self, proxy: Incomplete | None = None, as_dict: bool = False): ...
    def get_info(self, proxy: Incomplete | None = None) -> dict: ...
    def get_fast_info(self, proxy: Incomplete | None = None): ...
    @property
    def basic_info(self): ...
    def get_sustainability(self, proxy: Incomplete | None = None, as_dict: bool = False): ...
    def get_analyst_price_targets(self, proxy: Incomplete | None = None) -> dict: ...
    def get_earnings_estimate(self, proxy: Incomplete | None = None, as_dict: bool = False): ...
    def get_revenue_estimate(self, proxy: Incomplete | None = None, as_dict: bool = False): ...
    def get_earnings_history(self, proxy: Incomplete | None = None, as_dict: bool = False): ...
    def get_eps_trend(self, proxy: Incomplete | None = None, as_dict: bool = False): ...
    def get_eps_revisions(self, proxy: Incomplete | None = None, as_dict: bool = False): ...
    def get_growth_estimates(self, proxy: Incomplete | None = None, as_dict: bool = False): ...
    def get_earnings(self, proxy: Incomplete | None = None, as_dict: bool = False, freq: str = 'yearly'): ...
    def get_income_stmt(self, proxy: Incomplete | None = None, as_dict: bool = False, pretty: bool = False, freq: str = 'yearly'): ...
    def get_incomestmt(self, proxy: Incomplete | None = None, as_dict: bool = False, pretty: bool = False, freq: str = 'yearly'): ...
    def get_financials(self, proxy: Incomplete | None = None, as_dict: bool = False, pretty: bool = False, freq: str = 'yearly'): ...
    def get_balance_sheet(self, proxy: Incomplete | None = None, as_dict: bool = False, pretty: bool = False, freq: str = 'yearly'): ...
    def get_balancesheet(self, proxy: Incomplete | None = None, as_dict: bool = False, pretty: bool = False, freq: str = 'yearly'): ...
    def get_cash_flow(self, proxy: Incomplete | None = None, as_dict: bool = False, pretty: bool = False, freq: str = 'yearly') -> pd.DataFrame | dict: ...
    def get_cashflow(self, proxy: Incomplete | None = None, as_dict: bool = False, pretty: bool = False, freq: str = 'yearly'): ...
    def get_dividends(self, proxy: Incomplete | None = None, period: str = 'max') -> pd.Series: ...
    def get_capital_gains(self, proxy: Incomplete | None = None, period: str = 'max') -> pd.Series: ...
    def get_splits(self, proxy: Incomplete | None = None, period: str = 'max') -> pd.Series: ...
    def get_actions(self, proxy: Incomplete | None = None, period: str = 'max') -> pd.Series: ...
    def get_shares(self, proxy: Incomplete | None = None, as_dict: bool = False) -> pd.DataFrame | dict: ...
    def get_shares_full(self, start: Incomplete | None = None, end: Incomplete | None = None, proxy: Incomplete | None = None): ...
    def get_isin(self, proxy: Incomplete | None = None) -> str | None: ...
    def get_news(self, count: int = 10, tab: str = 'news', proxy: Incomplete | None = None) -> list: ...
    def get_earnings_dates(self, limit: int = 12, proxy: Incomplete | None = None) -> pd.DataFrame | None: ...
    def get_history_metadata(self, proxy: Incomplete | None = None) -> dict: ...
    def get_funds_data(self, proxy: Incomplete | None = None) -> FundsData | None: ...
