from . import Ticker as Ticker, multi as multi
from _typeshed import Incomplete

class Tickers:
    symbols: Incomplete
    tickers: Incomplete
    def __init__(self, tickers, session: Incomplete | None = None) -> None: ...
    def history(self, period: str = '1mo', interval: str = '1d', start: Incomplete | None = None, end: Incomplete | None = None, prepost: bool = False, actions: bool = True, auto_adjust: bool = True, repair: bool = False, proxy: Incomplete | None = None, threads: bool = True, group_by: str = 'column', progress: bool = True, timeout: int = 10, **kwargs): ...
    def download(self, period: str = '1mo', interval: str = '1d', start: Incomplete | None = None, end: Incomplete | None = None, prepost: bool = False, actions: bool = True, auto_adjust: bool = True, repair: bool = False, proxy: Incomplete | None = None, threads: bool = True, group_by: str = 'column', progress: bool = True, timeout: int = 10, **kwargs): ...
    def news(self): ...
