from _typeshed import Incomplete
from pandas.errors import PyperclipException

__all__ = ['copy', 'paste', 'waitForPaste', 'waitForNewPaste', 'set_clipboard', 'determine_clipboard']

class PyperclipTimeoutException(PyperclipException): ...

class CheckedCall:
    def __init__(self, f) -> None: ...
    def __call__(self, *args): ...
    def __setattr__(self, key, value) -> None: ...

def determine_clipboard(): ...
def set_clipboard(clipboard) -> None: ...

copy: Incomplete
paste: Incomplete

def waitForPaste(timeout: Incomplete | None = None): ...
def waitForNewPaste(timeout: Incomplete | None = None): ...
clipboard_get = paste
clipboard_set = copy
