from pandas import DataFrame as DataFrame
from pandas._libs.writers import convert_json_to_lines as convert_json_to_lines
from pandas._typing import IgnoreRaise as IgnoreRaise, Scalar as Scalar

def convert_to_line_delimits(s: str) -> str: ...
def nested_to_record(ds, prefix: str = '', sep: str = '.', level: int = 0, max_level: int | None = None): ...
def json_normalize(data: dict | list[dict], record_path: str | list | None = None, meta: str | list[str | list[str]] | None = None, meta_prefix: str | None = None, record_prefix: str | None = None, errors: IgnoreRaise = 'raise', sep: str = '.', max_level: int | None = None) -> DataFrame: ...
