from _typeshed import Incomplete

__all__ = ['seterr', 'geterr', 'setbufsize', 'getbufsize', 'seterrcall', 'geterrcall', 'errstate']

def seterr(all: Incomplete | None = None, divide: Incomplete | None = None, over: Incomplete | None = None, under: Incomplete | None = None, invalid: Incomplete | None = None): ...
def geterr(): ...
def setbufsize(size): ...
def getbufsize(): ...
def seterrcall(func): ...
def geterrcall(): ...

class _unspecified: ...

class errstate:
    def __init__(self, *, call=..., all: Incomplete | None = None, divide: Incomplete | None = None, over: Incomplete | None = None, under: Incomplete | None = None, invalid: Incomplete | None = None) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, *exc_info) -> None: ...
    def __call__(self, func): ...
