from _typeshed import Incomplete

__all__ = ['all', 'amax', 'amin', 'any', 'argmax', 'argmin', 'argpartition', 'argsort', 'around', 'choose', 'clip', 'compress', 'cumprod', 'cumsum', 'cumulative_prod', 'cumulative_sum', 'diagonal', 'mean', 'max', 'min', 'matrix_transpose', 'ndim', 'nonzero', 'partition', 'prod', 'ptp', 'put', 'ravel', 'repeat', 'reshape', 'resize', 'round', 'searchsorted', 'shape', 'size', 'sort', 'squeeze', 'std', 'sum', 'swapaxes', 'take', 'trace', 'transpose', 'var']

def take(a, indices, axis: Incomplete | None = None, out: Incomplete | None = None, mode: str = 'raise'): ...
def reshape(a, /, shape: Incomplete | None = None, order: str = 'C', *, newshape: Incomplete | None = None, copy: Incomplete | None = None): ...
def choose(a, choices, out: Incomplete | None = None, mode: str = 'raise'): ...
def repeat(a, repeats, axis: Incomplete | None = None): ...
def put(a, ind, v, mode: str = 'raise'): ...
def swapaxes(a, axis1, axis2): ...
def transpose(a, axes: Incomplete | None = None): ...
def matrix_transpose(x, /): ...
def partition(a, kth, axis: int = -1, kind: str = 'introselect', order: Incomplete | None = None): ...
def argpartition(a, kth, axis: int = -1, kind: str = 'introselect', order: Incomplete | None = None): ...
def sort(a, axis: int = -1, kind: Incomplete | None = None, order: Incomplete | None = None, *, stable: Incomplete | None = None): ...
def argsort(a, axis: int = -1, kind: Incomplete | None = None, order: Incomplete | None = None, *, stable: Incomplete | None = None): ...
def argmax(a, axis: Incomplete | None = None, out: Incomplete | None = None, *, keepdims=...): ...
def argmin(a, axis: Incomplete | None = None, out: Incomplete | None = None, *, keepdims=...): ...
def searchsorted(a, v, side: str = 'left', sorter: Incomplete | None = None): ...
def resize(a, new_shape): ...
def squeeze(a, axis: Incomplete | None = None): ...
def diagonal(a, offset: int = 0, axis1: int = 0, axis2: int = 1): ...
def trace(a, offset: int = 0, axis1: int = 0, axis2: int = 1, dtype: Incomplete | None = None, out: Incomplete | None = None): ...
def ravel(a, order: str = 'C'): ...
def nonzero(a): ...
def shape(a): ...
def compress(condition, a, axis: Incomplete | None = None, out: Incomplete | None = None): ...
def clip(a, a_min=..., a_max=..., out: Incomplete | None = None, *, min=..., max=..., **kwargs): ...
def sum(a, axis: Incomplete | None = None, dtype: Incomplete | None = None, out: Incomplete | None = None, keepdims=..., initial=..., where=...): ...
def any(a, axis: Incomplete | None = None, out: Incomplete | None = None, keepdims=..., *, where=...): ...
def all(a, axis: Incomplete | None = None, out: Incomplete | None = None, keepdims=..., *, where=...): ...
def cumulative_prod(x, /, *, axis: Incomplete | None = None, dtype: Incomplete | None = None, out: Incomplete | None = None, include_initial: bool = False): ...
def cumulative_sum(x, /, *, axis: Incomplete | None = None, dtype: Incomplete | None = None, out: Incomplete | None = None, include_initial: bool = False): ...
def cumsum(a, axis: Incomplete | None = None, dtype: Incomplete | None = None, out: Incomplete | None = None): ...
def ptp(a, axis: Incomplete | None = None, out: Incomplete | None = None, keepdims=...): ...
def max(a, axis: Incomplete | None = None, out: Incomplete | None = None, keepdims=..., initial=..., where=...): ...
def amax(a, axis: Incomplete | None = None, out: Incomplete | None = None, keepdims=..., initial=..., where=...): ...
def min(a, axis: Incomplete | None = None, out: Incomplete | None = None, keepdims=..., initial=..., where=...): ...
def amin(a, axis: Incomplete | None = None, out: Incomplete | None = None, keepdims=..., initial=..., where=...): ...
def prod(a, axis: Incomplete | None = None, dtype: Incomplete | None = None, out: Incomplete | None = None, keepdims=..., initial=..., where=...): ...
def cumprod(a, axis: Incomplete | None = None, dtype: Incomplete | None = None, out: Incomplete | None = None): ...
def ndim(a): ...
def size(a, axis: Incomplete | None = None): ...
def round(a, decimals: int = 0, out: Incomplete | None = None): ...
def around(a, decimals: int = 0, out: Incomplete | None = None): ...
def mean(a, axis: Incomplete | None = None, dtype: Incomplete | None = None, out: Incomplete | None = None, keepdims=..., *, where=...): ...
def std(a, axis: Incomplete | None = None, dtype: Incomplete | None = None, out: Incomplete | None = None, ddof: int = 0, keepdims=..., *, where=..., mean=..., correction=...): ...
def var(a, axis: Incomplete | None = None, dtype: Incomplete | None = None, out: Incomplete | None = None, ddof: int = 0, keepdims=..., *, where=..., mean=..., correction=...): ...
