from _typeshed import Incomplete

__all__ = ['logspace', 'linspace', 'geomspace']

def linspace(start, stop, num: int = 50, endpoint: bool = True, retstep: bool = False, dtype: Incomplete | None = None, axis: int = 0, *, device: Incomplete | None = None): ...
def logspace(start, stop, num: int = 50, endpoint: bool = True, base: float = 10.0, dtype: Incomplete | None = None, axis: int = 0): ...
def geomspace(start, stop, num: int = 50, endpoint: bool = True, dtype: Incomplete | None = None, axis: int = 0): ...
