import abc
import pandas as _pd
from ..data import YfData as YfData
from ..ticker import Ticker as Ticker
from _typeshed import Incomplete
from abc import ABC

class Domain(ABC, metaclass=abc.ABCMeta):
    proxy: Incomplete
    session: Incomplete
    def __init__(self, key: str, session: Incomplete | None = None, proxy: Incomplete | None = None) -> None: ...
    @property
    def key(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def symbol(self) -> str: ...
    @property
    def ticker(self) -> Ticker: ...
    @property
    def overview(self) -> dict: ...
    @property
    def top_companies(self) -> _pd.DataFrame | None: ...
    @property
    def research_reports(self) -> list[dict[str, str]]: ...
