from _typeshed import Incomplete

__test__: dict

class NDFrameIndexerBase:
    name: Incomplete
    ndim: Incomplete
    obj: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self): ...
    def __reduce_cython__(self, *args, **kwargs): ...
    def __setstate_cython__(self, *args, **kwargs): ...
